export type Country = { code: string; en: string; fr: string };

// Curated but broad list — searchable, no huge dropdown.
export const COUNTRIES: Country[] = [
  { code: "FR", en: "France", fr: "France" },
  { code: "BE", en: "Belgium", fr: "Belgique" },
  { code: "CH", en: "Switzerland", fr: "Suisse" },
  { code: "LU", en: "Luxembourg", fr: "Luxembourg" },
  { code: "CA", en: "Canada", fr: "Canada" },
  { code: "US", en: "United States", fr: "États-Unis" },
  { code: "GB", en: "United Kingdom", fr: "Royaume-Uni" },
  { code: "IE", en: "Ireland", fr: "Irlande" },
  { code: "ES", en: "Spain", fr: "Espagne" },
  { code: "PT", en: "Portugal", fr: "Portugal" },
  { code: "IT", en: "Italy", fr: "Italie" },
  { code: "DE", en: "Germany", fr: "Allemagne" },
  { code: "AT", en: "Austria", fr: "Autriche" },
  { code: "NL", en: "Netherlands", fr: "Pays-Bas" },
  { code: "DK", en: "Denmark", fr: "Danemark" },
  { code: "SE", en: "Sweden", fr: "Suède" },
  { code: "NO", en: "Norway", fr: "Norvège" },
  { code: "FI", en: "Finland", fr: "Finlande" },
  { code: "PL", en: "Poland", fr: "Pologne" },
  { code: "CZ", en: "Czechia", fr: "Tchéquie" },
  { code: "GR", en: "Greece", fr: "Grèce" },
  { code: "RO", en: "Romania", fr: "Roumanie" },
  { code: "TR", en: "Turkey", fr: "Turquie" },
  { code: "MA", en: "Morocco", fr: "Maroc" },
  { code: "DZ", en: "Algeria", fr: "Algérie" },
  { code: "TN", en: "Tunisia", fr: "Tunisie" },
  { code: "SN", en: "Senegal", fr: "Sénégal" },
  { code: "CI", en: "Ivory Coast", fr: "Côte d'Ivoire" },
  { code: "CM", en: "Cameroon", fr: "Cameroun" },
  { code: "MX", en: "Mexico", fr: "Mexique" },
  { code: "BR", en: "Brazil", fr: "Brésil" },
  { code: "AR", en: "Argentina", fr: "Argentine" },
  { code: "CO", en: "Colombia", fr: "Colombie" },
  { code: "CL", en: "Chile", fr: "Chili" },
  { code: "AU", en: "Australia", fr: "Australie" },
  { code: "NZ", en: "New Zealand", fr: "Nouvelle-Zélande" },
  { code: "JP", en: "Japan", fr: "Japon" },
  { code: "KR", en: "South Korea", fr: "Corée du Sud" },
  { code: "CN", en: "China", fr: "Chine" },
  { code: "IN", en: "India", fr: "Inde" },
  { code: "SG", en: "Singapore", fr: "Singapour" },
  { code: "AE", en: "United Arab Emirates", fr: "Émirats arabes unis" },
  { code: "SA", en: "Saudi Arabia", fr: "Arabie saoudite" },
  { code: "IL", en: "Israel", fr: "Israël" },
  { code: "EG", en: "Egypt", fr: "Égypte" },
  { code: "ZA", en: "South Africa", fr: "Afrique du Sud" },
];

export function countryName(c: Country, locale: string): string {
  return locale.startsWith("fr") ? c.fr : c.en;
}
